### ISSUE TITLE
User Authentication needs work

### ISSUE THREAD

**Issue by dimstar** [MarchosiasM/tentativeBoardGameApp#12]
## After doing a bunch of digging I think user auth should be done one of two ways:

1. with an async middleware for react components so that we don't end up with where we are now.
2. we should leverage local storage token for authentication so that we don't have t async call firebase. we could even beef this up with some user model validation/security.

#### areas effected...
`client/modules/App.js`
`client/modules/Auth/AuthActions.js`

#### and functions related...
`onAuthStateChanged()`
`fetchAuthUserRequest()`

**Comment by MarchosiasM** [comment]
@rperez2021 is currently working on this. 

Roberto are you tracking these issues?

**Comment by rperez2021** [comment]
Closing this, this has been resolved.
