### ISSUE TITLE
Search index.js reverted to include date search, but we want it 'hidden'

### ISSUE THREAD

**Issue by dimstar** [MarchosiasM/tentativeBoardGameApp#40]
Take a look [here](https://github.com/MarchosiasM/tentativeBoardGameApp/pull/39/commits/fb3ae8d964deb15af6706492d3287c3a308b954d) on one of your last commits. Basically it looks like a fetch got missed or something workflow wise got a little gacked up.

Let me know if you need moire info but essentially we want to preserve the what was done in this [PR](https://github.com/MarchosiasM/tentativeBoardGameApp/commit/cbcea7e43efeb8c75634ff917c1f321a1b8e40fc)

**Comment by dimstar** [comment]
@MarchosiasM this one is for you. let me know if you have Qs?

**Comment by MarchosiasM** [comment]
I'll look over it
